import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../style/globals.css'
import Headpage from './Header/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Headpage />
        <main>{children}</main>
      </body>
    </html>
  )
}
